services:
  - type: web
    name: mern-estate
    env: node
    buildCommand: 'npm run clean && npm run build'
    startCommand: 'npm start'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromSecret: mongo_uri
